language: node_js
node_js:
- '10'
- '11'
- '12'
- '13'
- lts/*
- node
deploy:
  provider: npm
  email: nessthehero@gmail.com
  api_key:
    secure: C0yVx8Tx0OjubqTsDj15ConFXRZgD+WNfEENXwae9WslIfyJmkEzFVBdy7Z1K/rN7Cj9eg6UZv4tpLYvYieNC8qx9iwXqKpW+o6591rcaKvcLe6FwZBiz1yGKqT+hmzvzP9noxJ8hkQw/Hm7ezijoqGzufDyRdD9Ac7Mu4rFILJ9GnJ0Lh13anWOxTSDUndnTTGmHSpymxv6yNA1b6WhGVPc/wPVwY18pdCSVzDaDcaezGPHU26EQjSsr85+eyYMq00oImovtOWDH2KYMxa+KXsSgvrgSs54XZ+x1t7eOvEHJmlZJpai/vElBee4jRfd3htwGwLITNF/wusrrgWk/2KtfnVbKDGEwZFF+Wlw7s5dz0IJlO2Hjbzmvj2TJSzkU5+dIS8OGIK+fz3JLt/jpF5wtXaw6d9TH32n2j4h1P3w0notkYKof/2fMNP/W+NxJKLjM3lYFIWVdHPKLbIeITdlWl2wMfJX1TeIqjjLjPvaJ4+ENaad3cqpryX4lyp96z8Bk9BIwRGE6hTNhwg3Ky4rkCaaKD5HT8UyJ3b5S0lg3GEqHGyhENXNKh8trrmM6oJaqoGiKUngARqE9WFYEGXBGcyElwga2IMd7TdBRo7oXizj2cIblU2M09O5jywDAW3jM37KMGQQ6aTcbR3yBwPcEgsYJmunZsX9r8Fhz5Q=
  on:
    tags: true
    repo: BarkleyREI/brei-pattern-scaffold
  skip_cleanup: 'true'
